<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>14</LangVersion>
		
		<Description>A set of math functions, formulas, and the like to help with math calculations within a game or similar application</Description>
		<PackageTags>OpenSourceKingdom, OpenSource, Petra, Game, Framework, Suite, Tool, Math, Equation, Calculate, Calculator, Formula, Function, Economy</PackageTags>
		<Title>OSK.Petra.Math.Formulas</Title>
		<Authors>BlankDev117</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/OpenSourceKingdom/OSK.Petra.Math</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OSK.Hexagonal.MetaData" Version="1.0.0" />
	  <PackageReference Include="PolySharp" Version="1.16.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
