<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>14</LangVersion>
		
		<Description>An extension that combines the math formulas with provisions to accomodate economy provision scaling</Description>
		<PackageTags>OpenSourceKingdom, OpenSource, Petra, Game, Framework, Suite, Tool, Math, Equation, Calculate, Calculator, Scale, Economy, Provision</PackageTags>
		<Title>OSK.Extensions.Petra.Calculators.Provisions</Title>
		<Authors>BlankDev117</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/OpenSourceKingdom/OSK.Petra.Calculators</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="OSK.Petra.Provisions" Version="0.3.0" />
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\OSK.Petra.Math.Formulas\OSK.Petra.Math.Formulas.csproj" />
	</ItemGroup>

</Project>
